// Code generated by hertz generator.

package transfer

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/rainbow_bridge/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _transferMw() []app.HandlerFunc {
	// your code...
	return nil
}

//nolint:unused // auto-generated middleware, may be used in future routes
func _exportMw() []app.HandlerFunc {
	// your code...
	return nil
}

//nolint:unused // auto-generated middleware, may be used in future routes
func _export0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

//nolint:unused // auto-generated middleware, may be used in future routes
func _staticMw() []app.HandlerFunc {
	// your code...
	return nil
}

//nolint:unused // auto-generated middleware, may be used in future routes
func _exportstaticallMw() []app.HandlerFunc {
	// your code...
	return nil
}

//nolint:unused // auto-generated middleware, may be used in future routes
func _exportstaticselectedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _importMw() []app.HandlerFunc {
	return middleware.WriteLockMw()
}

func _migrateMw() []app.HandlerFunc {
	return middleware.WriteLockMw()
}

func _exportselectiveMw() []app.HandlerFunc {
	return middleware.WriteLockMw()
}

func _exporttreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _importpreviewMw() []app.HandlerFunc {
	return middleware.WriteLockMw()
}

func _importselectiveMw() []app.HandlerFunc {
	return middleware.WriteLockMw()
}
