// Code generated by hertz generator.

package system_config

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	common "github.com/yi-nology/rainbow_bridge/biz/model/common"
	system_config "github.com/yi-nology/rainbow_bridge/biz/model/system_config"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// Get .
// @router /api/v1/system-config/get [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	var req system_config.GetSystemConfigRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}
	if req.ConfigKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("config_key is required"))
		return
	}

	cfg, err := svc.GetSystemConfig(handler.EnrichContext(ctx, c), req.EnvironmentKey, req.ConfigKey)
	if err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrSystemConfigNotFound) {
			status = consts.StatusNotFound
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &system_config.SystemConfigResponse{
		OperateResponse: &common.OperateResponse{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		SystemConfig: &system_config.SystemConfig{
			EnvironmentKey: cfg.EnvironmentKey,
			ConfigKey:      cfg.ConfigKey,
			ConfigValue:    cfg.ConfigValue,
			Remark:         cfg.Remark,
		},
	}
	c.JSON(consts.StatusOK, resp)
}

// Update .
// @router /api/v1/system-config/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var req system_config.UpdateSystemConfigRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.SystemConfig == nil {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("system_config is required"))
		return
	}
	if req.SystemConfig.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}
	if req.SystemConfig.ConfigKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("config_key is required"))
		return
	}

	if err := svc.UpdateSystemConfig(
		handler.EnrichContext(ctx, c),
		req.SystemConfig.EnvironmentKey,
		req.SystemConfig.ConfigKey,
		req.SystemConfig.ConfigValue,
	); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrInvalidSystemConfigKey) {
			status = consts.StatusBadRequest
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &system_config.SystemConfigResponse{
		OperateResponse: &common.OperateResponse{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		SystemConfig: req.SystemConfig,
	}
	c.JSON(consts.StatusOK, resp)
}

// List .
// @router /api/v1/system-config/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req system_config.ListSystemConfigRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	configs, err := svc.ListSystemConfigsByEnv(handler.EnrichContext(ctx, c), req.EnvironmentKey)
	if err != nil {
		handler.RespondError(c, consts.StatusInternalServerError, err)
		return
	}

	list := make([]*system_config.SystemConfig, 0, len(configs))
	for _, cfg := range configs {
		list = append(list, &system_config.SystemConfig{
			EnvironmentKey: cfg.EnvironmentKey,
			ConfigKey:      cfg.ConfigKey,
			ConfigValue:    cfg.ConfigValue,
			Remark:         cfg.Remark,
		})
	}

	resp := &system_config.SystemConfigListResponse{
		List: list,
	}
	c.JSON(consts.StatusOK, resp)
}
