// Code generated by hertz generator.

package pipeline

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	common "github.com/yi-nology/rainbow_bridge/biz/model/common"
	pipeline "github.com/yi-nology/rainbow_bridge/biz/model/pipeline"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// Create .
// @router /api/v1/pipeline/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var req pipeline.CreatePipelineRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.Pipeline == nil || req.Pipeline.PipelineKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("pipeline_key is required"))
		return
	}
	if req.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	if err := svc.AddPipeline(handler.EnrichContext(ctx, c), req.EnvironmentKey, req.Pipeline); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrPipelineKeyExists) {
			status = consts.StatusBadRequest
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &pipeline.PipelineResponse{
		OperateResponse: &common.OperateResponse{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Pipeline: req.Pipeline,
	}
	c.JSON(consts.StatusOK, resp)
}

// Update .
// @router /api/v1/pipeline/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var req pipeline.UpdatePipelineRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.Pipeline == nil || req.Pipeline.PipelineKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("pipeline_key is required"))
		return
	}
	if req.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	if err := svc.UpdatePipeline(handler.EnrichContext(ctx, c), req.EnvironmentKey, req.Pipeline); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrPipelineNotFound) {
			status = consts.StatusNotFound
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &pipeline.PipelineResponse{
		OperateResponse: &common.OperateResponse{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Pipeline: req.Pipeline,
	}
	c.JSON(consts.StatusOK, resp)
}

// Delete .
// @router /api/v1/pipeline/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	var req pipeline.DeletePipelineRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.PipelineKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("pipeline_key is required"))
		return
	}
	if req.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	if err := svc.DeletePipeline(handler.EnrichContext(ctx, c), req.EnvironmentKey, req.PipelineKey); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrPipelineNotFound) {
			status = consts.StatusNotFound
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &common.OperateResponse{
		Code: consts.StatusOK,
		Msg:  "success",
	}
	c.JSON(consts.StatusOK, resp)
}

// List .
// @router /api/v1/pipeline/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req pipeline.ListPipelineRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	// Pipeline data is now environment-scoped
	if req.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	var isActivePtr *bool
	if req.IsActive {
		isActivePtr = &req.IsActive
	}

	list, err := svc.ListPipelines(handler.EnrichContext(ctx, c), req.EnvironmentKey, isActivePtr)
	if err != nil {
		handler.RespondError(c, consts.StatusInternalServerError, err)
		return
	}

	resp := &pipeline.PipelineListResponse{
		List: list,
	}
	c.JSON(consts.StatusOK, resp)
}

// Detail .
// @router /api/v1/pipeline/detail [GET]
func Detail(ctx context.Context, c *app.RequestContext) {
	var req pipeline.PipelineDetailRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.PipelineKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("pipeline_key is required"))
		return
	}
	if req.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	pl, err := svc.GetPipeline(handler.EnrichContext(ctx, c), req.EnvironmentKey, req.PipelineKey)
	if err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrPipelineNotFound) {
			status = consts.StatusNotFound
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &pipeline.PipelineDetailResponse{
		Detail: pl,
	}
	c.JSON(consts.StatusOK, resp)
}
