// Code generated by hertz generator.

package pipeline

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	pipeline "github.com/yi-nology/rainbow_bridge/biz/model/pipeline"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// Create .
// @router /api/v1/pipeline/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var req pipeline.CreatePipelineRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	if req.Pipeline == nil || req.Pipeline.PipelineKey == "" {
		c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "pipeline_key is required",
		})
		return
	}
	if req.EnvironmentKey == "" {
		c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}

	if err := svc.AddPipeline(handler.EnrichContext(ctx, c), req.EnvironmentKey, req.Pipeline); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrPipelineKeyExists) {
			status = consts.StatusBadRequest
		}
		c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &pipeline.PipelineData{Pipeline: req.Pipeline},
	})
}

// Update .
// @router /api/v1/pipeline/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var req pipeline.UpdatePipelineRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	if req.Pipeline == nil || req.Pipeline.PipelineKey == "" {
		c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "pipeline_key is required",
		})
		return
	}
	if req.EnvironmentKey == "" {
		c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}

	if err := svc.UpdatePipeline(handler.EnrichContext(ctx, c), req.EnvironmentKey, req.Pipeline); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrPipelineNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &pipeline.PipelineResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &pipeline.PipelineData{Pipeline: req.Pipeline},
	})
}

// Delete .
// @router /api/v1/pipeline/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	var req pipeline.DeletePipelineRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &pipeline.DeletePipelineResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	if req.PipelineKey == "" {
		c.JSON(consts.StatusOK, &pipeline.DeletePipelineResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "pipeline_key is required",
		})
		return
	}
	if req.EnvironmentKey == "" {
		c.JSON(consts.StatusOK, &pipeline.DeletePipelineResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}

	if err := svc.DeletePipeline(handler.EnrichContext(ctx, c), req.EnvironmentKey, req.PipelineKey); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrPipelineNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(consts.StatusOK, &pipeline.DeletePipelineResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &pipeline.DeletePipelineResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
	})
}

// List .
// @router /api/v1/pipeline/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req pipeline.ListPipelineRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &pipeline.PipelineListResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	// Pipeline data is now environment-scoped
	if req.EnvironmentKey == "" {
		c.JSON(consts.StatusOK, &pipeline.PipelineListResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}

	var isActivePtr *bool
	if req.IsActive {
		isActivePtr = &req.IsActive
	}

	list, err := svc.ListPipelines(handler.EnrichContext(ctx, c), req.EnvironmentKey, isActivePtr)
	if err != nil {
		c.JSON(consts.StatusOK, &pipeline.PipelineListResponse{
			Code:  consts.StatusInternalServerError,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &pipeline.PipelineListResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &pipeline.PipelineListData{
			Total: int32(len(list)),
			List:  list,
		},
	})
}

// Detail .
// @router /api/v1/pipeline/detail [GET]
func Detail(ctx context.Context, c *app.RequestContext) {
	var req pipeline.PipelineDetailRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &pipeline.PipelineDetailResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	if req.PipelineKey == "" {
		c.JSON(consts.StatusOK, &pipeline.PipelineDetailResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "pipeline_key is required",
		})
		return
	}
	if req.EnvironmentKey == "" {
		c.JSON(consts.StatusOK, &pipeline.PipelineDetailResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}

	pl, err := svc.GetPipeline(handler.EnrichContext(ctx, c), req.EnvironmentKey, req.PipelineKey)
	if err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrPipelineNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(consts.StatusOK, &pipeline.PipelineDetailResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &pipeline.PipelineDetailResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &pipeline.PipelineData{Pipeline: pl},
	})
}
