// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	asset "github.com/yi-nology/rainbow_bridge/biz/handler/asset"
	"github.com/yi-nology/rainbow_bridge/biz/handler/transfer"
)

// customizedRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	// 修复 IDL 自动生成的 /{file_id} 语法在某些 Hertz 版本下无法正确解析参数的问题
	// 同时支持带文件名的路径，以便 Nginx 静态服务识别
	r.GET("/api/v1/asset/file/:file_id", asset.GetFile)
	r.GET("/api/v1/asset/file/:file_id/*filename", asset.GetFile)

	// Transfer API extensions
	r.GET("/api/v1/transfer/export-tree", transfer.ExportTree)
	r.POST("/api/v1/transfer/export", transfer.ExportSelective)
	r.POST("/api/v1/transfer/import-preview", transfer.ImportPreview)
	r.POST("/api/v1/transfer/import-selective", transfer.ImportSelective)
}
