// Code generated by hertz generator.

package runtime

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	runtime "github.com/yi-nology/rainbow_bridge/biz/model/runtime"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// GetConfig .
// @router /api/v1/runtime/config [GET]
func GetConfig(ctx context.Context, c *app.RequestContext) {
	// 从 header 获取参数
	environmentKey := strings.TrimSpace(string(c.GetHeader("x-environment")))
	pipelineKey := strings.TrimSpace(string(c.GetHeader("x-pipeline")))

	// 参数验证
	if environmentKey == "" {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "x-environment header is required",
		})
		return
	}
	if pipelineKey == "" {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "x-pipeline header is required",
		})
		return
	}

	// 调用 service 层
	resp, err := svc.GetRuntimeConfig(handler.EnrichContext(ctx, c), environmentKey, pipelineKey)
	if err != nil {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusInternalServerError,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	// 自定义响应结构，处理 JSON 对象
	type CustomResourceConfig struct {
		ResourceKey    string      `json:"resource_key"`
		Alias          string      `json:"alias"`
		Name           string      `json:"name"`
		EnvironmentKey string      `json:"environment_key"`
		PipelineKey    string      `json:"pipeline_key"`
		Content        interface{} `json:"content"`
		Type           string      `json:"type"`
		Remark         string      `json:"remark"`
		IsPerm         bool        `json:"is_perm"`
	}

	type CustomRuntimeConfigData struct {
		Configs      []CustomResourceConfig `json:"configs"`
		Environment  *runtime.EnvironmentInfo `json:"environment"`
	}

	type CustomRuntimeConfigResponse struct {
		Code    int32                    `json:"code"`
		Msg     string                   `json:"msg"`
		Error   string                   `json:"error"`
		Data    CustomRuntimeConfigData  `json:"data"`
	}

	// 转换配置数据
	customConfigs := make([]CustomResourceConfig, len(resp.Data.Configs))
	for i, cfg := range resp.Data.Configs {
		customConfig := CustomResourceConfig{
			ResourceKey:    cfg.ResourceKey,
			Alias:          cfg.Alias,
			Name:           cfg.Name,
			EnvironmentKey: cfg.EnvironmentKey,
			PipelineKey:    cfg.PipelineKey,
			Type:           cfg.Type,
			Remark:         cfg.Remark,
			IsPerm:         cfg.IsPerm,
		}

		// 对于 object 和 keyvalue 类型，解析为 JSON 对象
		normalizedType := strings.ToLower(strings.TrimSpace(cfg.Type))
		switch normalizedType {
		case "object", "keyvalue", "json", "config", "kv", "key-value", "键值对":
			var content interface{}
			if err := json.Unmarshal([]byte(cfg.Content), &content); err == nil {
				customConfig.Content = content
			} else {
				customConfig.Content = cfg.Content
			}
		default:
			customConfig.Content = cfg.Content
		}

		customConfigs[i] = customConfig
	}

	// 构建自定义响应
	customResponse := CustomRuntimeConfigResponse{
		Code:   resp.Code,
		Msg:    resp.Msg,
		Error:  resp.Error,
		Data: CustomRuntimeConfigData{
			Configs:     customConfigs,
			Environment: resp.Data.Environment,
		},
	}

	c.JSON(consts.StatusOK, customResponse)
}

// ExportStatic .
// @router /api/v1/runtime/static [GET]
func ExportStatic(ctx context.Context, c *app.RequestContext) {
	// 从 query 参数获取
	environmentKey := strings.TrimSpace(c.Query("environment_key"))
	pipelineKey := strings.TrimSpace(c.Query("pipeline_key"))

	// 参数验证
	if environmentKey == "" {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}
	if pipelineKey == "" {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "pipeline_key is required",
		})
		return
	}

	// 调用 service 层
	data, filename, err := svc.ExportStaticPackage(handler.EnrichContext(ctx, c), environmentKey, pipelineKey)
	if err != nil {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusInternalServerError,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	// 返回 zip 文件
	c.Header("Content-Type", "application/zip")
	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	c.Data(consts.StatusOK, "application/zip", data)
}

// GetOverview .
// @router /api/v1/runtime/overview [GET]
func GetOverview(ctx context.Context, c *app.RequestContext) {
	resp, err := svc.GetRuntimeOverview(handler.EnrichContext(ctx, c))
	if err != nil {
		c.JSON(consts.StatusOK, &runtime.RuntimeOverviewResponse{
			Code:  consts.StatusInternalServerError,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, resp)
}
