// Code generated by hertz generator.

package runtime

import (
	"context"
	"fmt"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	runtime "github.com/yi-nology/rainbow_bridge/biz/model/runtime"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// GetConfig .
// @router /api/v1/runtime/config [GET]
func GetConfig(ctx context.Context, c *app.RequestContext) {
	// 从 header 获取参数
	environmentKey := strings.TrimSpace(string(c.GetHeader("x-environment")))
	pipelineKey := strings.TrimSpace(string(c.GetHeader("x-pipeline")))

	// 参数验证
	if environmentKey == "" {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "x-environment header is required",
		})
		return
	}
	if pipelineKey == "" {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "x-pipeline header is required",
		})
		return
	}

	// 调用 service 层
	resp, err := svc.GetRuntimeConfig(handler.EnrichContext(ctx, c), environmentKey, pipelineKey)
	if err != nil {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusInternalServerError,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// ExportStatic .
// @router /api/v1/runtime/static [GET]
func ExportStatic(ctx context.Context, c *app.RequestContext) {
	// 从 query 参数获取
	environmentKey := strings.TrimSpace(c.Query("environment_key"))
	pipelineKey := strings.TrimSpace(c.Query("pipeline_key"))

	// 参数验证
	if environmentKey == "" {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}
	if pipelineKey == "" {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "pipeline_key is required",
		})
		return
	}

	// 调用 service 层
	data, filename, err := svc.ExportStaticPackage(handler.EnrichContext(ctx, c), environmentKey, pipelineKey)
	if err != nil {
		c.JSON(consts.StatusOK, &runtime.RuntimeConfigResponse{
			Code:  consts.StatusInternalServerError,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	// 返回 zip 文件
	c.Header("Content-Type", "application/zip")
	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	c.Data(consts.StatusOK, "application/zip", data)
}

// GetOverview .
// @router /api/v1/runtime/overview [GET]
func GetOverview(ctx context.Context, c *app.RequestContext) {
	resp, err := svc.GetRuntimeOverview(handler.EnrichContext(ctx, c))
	if err != nil {
		c.JSON(consts.StatusOK, &runtime.RuntimeOverviewResponse{
			Code:  consts.StatusInternalServerError,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, resp)
}
