apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rainbow-bridge-data
  labels:
    app: rainbow-bridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
