// Code generated by hertz generator.

package version

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getversionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _versionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlatestreleaseMw() []app.HandlerFunc {
	// your code...
	return nil
}
