// Code generated by hertz generator.

package asset

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/yi-nology/rainbow_bridge/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _assetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	return middleware.WriteLockMw()
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfileMw() []app.HandlerFunc {
	// your code...
	return nil
}
