// Code generated by hertz generator.

package environment

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	environment "github.com/yi-nology/rainbow_bridge/biz/model/environment"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// Create .
// @router /api/v1/environment/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var req environment.CreateEnvironmentRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &environment.EnvironmentResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	if req.Environment == nil || req.Environment.EnvironmentKey == "" {
		c.JSON(consts.StatusOK, &environment.EnvironmentResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}

	if err := svc.AddEnvironment(handler.EnrichContext(ctx, c), req.Environment); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrEnvironmentKeyExists) {
			status = consts.StatusBadRequest
		}
		c.JSON(consts.StatusOK, &environment.EnvironmentResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &environment.EnvironmentResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &environment.EnvironmentData{Environment: req.Environment},
	})
}

// Update .
// @router /api/v1/environment/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var req environment.UpdateEnvironmentRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &environment.EnvironmentResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	if req.Environment == nil || req.Environment.EnvironmentKey == "" {
		c.JSON(consts.StatusOK, &environment.EnvironmentResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}

	if err := svc.UpdateEnvironment(handler.EnrichContext(ctx, c), req.Environment); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrEnvironmentNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(consts.StatusOK, &environment.EnvironmentResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &environment.EnvironmentResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &environment.EnvironmentData{Environment: req.Environment},
	})
}

// Delete .
// @router /api/v1/environment/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	var req environment.DeleteEnvironmentRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &environment.DeleteEnvironmentResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	if req.EnvironmentKey == "" {
		c.JSON(consts.StatusOK, &environment.DeleteEnvironmentResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}

	if err := svc.DeleteEnvironment(handler.EnrichContext(ctx, c), req.EnvironmentKey); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrEnvironmentNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(consts.StatusOK, &environment.DeleteEnvironmentResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &environment.DeleteEnvironmentResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
	})
}

// List .
// @router /api/v1/environment/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req environment.ListEnvironmentRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &environment.EnvironmentListResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	var isActivePtr *bool
	if req.IsActive {
		isActivePtr = &req.IsActive
	}

	list, err := svc.ListEnvironments(handler.EnrichContext(ctx, c), isActivePtr)
	if err != nil {
		c.JSON(consts.StatusOK, &environment.EnvironmentListResponse{
			Code:  consts.StatusInternalServerError,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &environment.EnvironmentListResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &environment.EnvironmentListData{
			Total: int32(len(list)),
			List:  list,
		},
	})
}

// Detail .
// @router /api/v1/environment/detail [GET]
func Detail(ctx context.Context, c *app.RequestContext) {
	var req environment.EnvironmentDetailRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusOK, &environment.EnvironmentDetailResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	if req.EnvironmentKey == "" {
		c.JSON(consts.StatusOK, &environment.EnvironmentDetailResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key is required",
		})
		return
	}

	env, err := svc.GetEnvironment(handler.EnrichContext(ctx, c), req.EnvironmentKey)
	if err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrEnvironmentNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(consts.StatusOK, &environment.EnvironmentDetailResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}

	c.JSON(consts.StatusOK, &environment.EnvironmentDetailResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &environment.EnvironmentData{Environment: env},
	})
}
