// Code generated by hertz generator.

package environment

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	common "github.com/yi-nology/rainbow_bridge/biz/model/common"
	environment "github.com/yi-nology/rainbow_bridge/biz/model/environment"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// Create .
// @router /api/v1/environment/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var req environment.CreateEnvironmentRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.Environment == nil || req.Environment.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	if err := svc.AddEnvironment(handler.EnrichContext(ctx, c), req.Environment); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrEnvironmentKeyExists) {
			status = consts.StatusBadRequest
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &environment.EnvironmentResponse{
		OperateResponse: &common.OperateResponse{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Environment: req.Environment,
	}
	c.JSON(consts.StatusOK, resp)
}

// Update .
// @router /api/v1/environment/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var req environment.UpdateEnvironmentRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.Environment == nil || req.Environment.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	if err := svc.UpdateEnvironment(handler.EnrichContext(ctx, c), req.Environment); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrEnvironmentNotFound) {
			status = consts.StatusNotFound
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &environment.EnvironmentResponse{
		OperateResponse: &common.OperateResponse{
			Code: consts.StatusOK,
			Msg:  "success",
		},
		Environment: req.Environment,
	}
	c.JSON(consts.StatusOK, resp)
}

// Delete .
// @router /api/v1/environment/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	var req environment.DeleteEnvironmentRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	if err := svc.DeleteEnvironment(handler.EnrichContext(ctx, c), req.EnvironmentKey); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrEnvironmentNotFound) {
			status = consts.StatusNotFound
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &common.OperateResponse{
		Code: consts.StatusOK,
		Msg:  "success",
	}
	c.JSON(consts.StatusOK, resp)
}

// List .
// @router /api/v1/environment/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req environment.ListEnvironmentRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	var isActivePtr *bool
	if req.IsActive {
		isActivePtr = &req.IsActive
	}

	list, err := svc.ListEnvironments(handler.EnrichContext(ctx, c), isActivePtr)
	if err != nil {
		handler.RespondError(c, consts.StatusInternalServerError, err)
		return
	}

	resp := &environment.EnvironmentListResponse{
		List: list,
	}
	c.JSON(consts.StatusOK, resp)
}

// Detail .
// @router /api/v1/environment/detail [GET]
func Detail(ctx context.Context, c *app.RequestContext) {
	var req environment.EnvironmentDetailRequest
	if err := c.BindAndValidate(&req); err != nil {
		handler.RespondError(c, consts.StatusBadRequest, err)
		return
	}

	if req.EnvironmentKey == "" {
		handler.RespondError(c, consts.StatusBadRequest, errors.New("environment_key is required"))
		return
	}

	env, err := svc.GetEnvironment(handler.EnrichContext(ctx, c), req.EnvironmentKey)
	if err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrEnvironmentNotFound) {
			status = consts.StatusNotFound
		}
		handler.RespondError(c, status, err)
		return
	}

	resp := &environment.EnvironmentDetailResponse{
		Detail: env,
	}
	c.JSON(consts.StatusOK, resp)
}
