// Code generated by hertz generator.

package runtime

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _runtimeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exportstaticMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getoverviewMw() []app.HandlerFunc {
	// your code...
	return nil
}
