// Code generated by hertz generator. DO NOT EDIT.

package resourcepb

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handlerpb "github.com/yi-nology/rainbow_bridge/biz/handler/resourcepb"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

var resourceHandler *handlerpb.ResourceService

// SetResourceServiceHandler injects the protobuf-backed handler used during registration.
func SetResourceServiceHandler(h *handlerpb.ResourceService) {
	resourceHandler = h
}

func registerResourceRoutes(r *server.Hertz) {
	if resourceHandler == nil {
		return
	}

	resources := r.Group("/api/v1/resources")
	resources.POST("", resourceHandler.AddConfig)
	resources.PUT("", resourceHandler.UpdateConfig)
	resources.DELETE("", resourceHandler.DeleteConfig)
	resources.GET("", resourceHandler.ListConfigs)
	resources.GET("/detail", resourceHandler.GetConfigDetail)
	resources.POST("/import", resourceHandler.ImportConfigs)
	resources.GET("/export", resourceHandler.ExportConfigs)
	resources.GET("/business-keys", resourceHandler.ListBusinessKeys)

	assets := r.Group("/api/v1/assets")
	assets.GET("", resourceHandler.ListAssets)
}
