// Code generated by hertz generator. DO NOT EDIT.

package resourcepb

import "github.com/cloudwego/hertz/pkg/app/server"

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {
	registerResourceRoutes(r)
}
