// Code generated by hertz generator.

package transfer

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	common "github.com/yi-nology/rainbow_bridge/biz/model/common"
	transfer "github.com/yi-nology/rainbow_bridge/biz/model/transfer"
)

// Import .
// @router /api/v1/transfer/import [POST]
func Import(ctx context.Context, c *app.RequestContext) {
	var err error
	var req transfer.ImportRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(transfer.ImportResponse)

	c.JSON(consts.StatusOK, resp)
}

// Export .
// @router /api/v1/transfer/export [GET]
func Export(ctx context.Context, c *app.RequestContext) {
	var err error
	var req transfer.ExportRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(transfer.ExportResponse)

	c.JSON(consts.StatusOK, resp)
}

// ExportStaticSelected .
// @router /api/v1/transfer/export/static/selected [GET]
func ExportStaticSelected(ctx context.Context, c *app.RequestContext) {
	var err error
	var req transfer.ExportRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.OperateResponse)

	c.JSON(consts.StatusOK, resp)
}

// ExportStaticAll .
// @router /api/v1/transfer/export/static/all [GET]
func ExportStaticAll(ctx context.Context, c *app.RequestContext) {
	var err error
	var req transfer.ExportRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.OperateResponse)

	c.JSON(consts.StatusOK, resp)
}
