#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
PROTO_DIR="$ROOT_DIR/proto"

protoc -I"$PROTO_DIR" --go_out=paths=source_relative:"$ROOT_DIR" \
  "$PROTO_DIR/google/api/http.proto" \
  "$PROTO_DIR/google/api/annotations.proto" \
  "$PROTO_DIR/resource.proto"

mv "$ROOT_DIR/resource.pb.go" "$ROOT_DIR/api/resourcepb/resource.pb.go"

if command -v goimports >/dev/null 2>&1; then
  goimports -w "$ROOT_DIR/api/resourcepb/resource.pb.go" "$ROOT_DIR/google/api"
else
  gofmt -w "$ROOT_DIR/api/resourcepb/resource.pb.go" "$ROOT_DIR/google/api"
fi

if command -v hz >/dev/null 2>&1; then
  hz update \
    --handler_dir biz/handler \
    --model_dir biz/model \
    --idl proto/resource.proto

  cat <<'EOF' >"$ROOT_DIR/biz/router/resourcepb/resource.go"
// Code generated by hertz generator. DO NOT EDIT.

package resourcepb

import "github.com/cloudwego/hertz/pkg/app/server"

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {
	registerResourceRoutes(r)
}
EOF

  cat <<'EOF' >"$ROOT_DIR/biz/handler/resourcepb/resource_service.go"
// Code generated by hertz generator.

package resourcepb
EOF

  gofmt -w "$ROOT_DIR/biz/router/resourcepb/resource.go" "$ROOT_DIR/biz/handler/resourcepb/resource_service.go"
fi
