// Code generated by hertz generator.

package asset

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	asset "github.com/yi-nology/rainbow_bridge/biz/model/asset"
	common "github.com/yi-nology/rainbow_bridge/biz/model/common"
)

// List .
// @router /api/v1/asset/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req asset.ListAssetRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(asset.AssetListResponse)

	c.JSON(consts.StatusOK, resp)
}

// Upload .
// @router /api/v1/asset/upload [POST]
func Upload(ctx context.Context, c *app.RequestContext) {
	var err error
	var req asset.ListAssetRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(asset.UploadAssetResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetFile .
// @router /api/v1/asset/file/{file_id} [GET]
func GetFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req asset.GetFileRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.OperateResponse)

	c.JSON(consts.StatusOK, resp)
}
