// Code generated by hertz generator.

package config

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	common "github.com/yi-nology/rainbow_bridge/biz/model/common"
	config "github.com/yi-nology/rainbow_bridge/biz/model/config"
)

// Create .
// @router /api/v1/config/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	var err error
	var req config.CreateConfigRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(config.ConfigResponse)

	c.JSON(consts.StatusOK, resp)
}

// Update .
// @router /api/v1/config/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	var err error
	var req config.UpdateConfigRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(config.ConfigResponse)

	c.JSON(consts.StatusOK, resp)
}

// Delete .
// @router /api/v1/config/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	var err error
	var req config.DeleteConfigRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.OperateResponse)

	c.JSON(consts.StatusOK, resp)
}

// List .
// @router /api/v1/config/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req config.ListConfigRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(config.ConfigListResponse)

	c.JSON(consts.StatusOK, resp)
}

// Detail .
// @router /api/v1/config/detail [GET]
func Detail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req config.ConfigDetailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(config.ConfigDetailResponse)

	c.JSON(consts.StatusOK, resp)
}
