// Code generated by hertz generator.

package config

import (
	"context"
	"errors"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	"github.com/yi-nology/rainbow_bridge/biz/model/common"
	"github.com/yi-nology/rainbow_bridge/biz/model/config"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// Create .
// @router /api/v1/config/create [POST]
func Create(ctx context.Context, c *app.RequestContext) {
	req := &config.CreateConfigRequest{}
	if err := c.BindJSON(req); err != nil {
		c.JSON(consts.StatusOK, &config.ConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}
	cfg, err := svc.AddConfig(handler.EnrichContext(ctx, c), req.GetConfig())
	if err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrConfigAliasExists) {
			status = consts.StatusBadRequest
		}
		c.JSON(consts.StatusOK, &config.ConfigResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}
	c.JSON(consts.StatusOK, &config.ConfigResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &config.ConfigData{Config: cfg},
	})
}

// Update .
// @router /api/v1/config/update [POST]
func Update(ctx context.Context, c *app.RequestContext) {
	req := &config.UpdateConfigRequest{}
	if err := c.BindJSON(req); err != nil {
		c.JSON(consts.StatusOK, &config.ConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}
	if req.Config == nil || req.Config.ResourceKey == "" {
		c.JSON(consts.StatusOK, &config.ConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "resource_key is required",
		})
		return
	}
	cfg, err := svc.UpdateConfig(handler.EnrichContext(ctx, c), req.GetConfig())
	if err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrResourceNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(consts.StatusOK, &config.ConfigResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}
	c.JSON(consts.StatusOK, &config.ConfigResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &config.ConfigData{Config: cfg},
	})
}

// Delete .
// @router /api/v1/config/delete [POST]
func Delete(ctx context.Context, c *app.RequestContext) {
	req := &config.DeleteConfigRequest{}
	if err := c.BindJSON(req); err != nil {
		c.JSON(consts.StatusOK, &config.DeleteConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}
	if req.EnvironmentKey == "" || req.PipelineKey == "" || req.ResourceKey == "" {
		c.JSON(consts.StatusOK, &config.DeleteConfigResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key, pipeline_key and resource_key are required",
		})
		return
	}
	if err := svc.DeleteConfig(handler.EnrichContext(ctx, c), req.GetEnvironmentKey(), req.GetPipelineKey(), req.GetResourceKey()); err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrResourceNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(consts.StatusOK, &config.DeleteConfigResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}
	c.JSON(consts.StatusOK, &config.DeleteConfigResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
	})
}

// List .
// @router /api/v1/config/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	req := &config.ListConfigRequest{
		EnvironmentKey: c.Query("environment_key"),
		PipelineKey:    c.Query("pipeline_key"),
		Type:           c.Query("type"),
		MinVersion:     c.Query("min_version"),
		MaxVersion:     c.Query("max_version"),
	}
	if req.EnvironmentKey == "" || req.PipelineKey == "" {
		c.JSON(consts.StatusOK, &config.ConfigListResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key and pipeline_key are required",
		})
		return
	}
	if val := c.Query("is_latest"); val != "" {
		parsed, err := strconv.ParseBool(val)
		if err != nil {
			c.JSON(consts.StatusOK, &config.ConfigListResponse{
				Code:  consts.StatusBadRequest,
				Msg:   "error",
				Error: err.Error(),
			})
			return
		}
		req.IsLatest = parsed
	}

	list, err := svc.ListConfigs(handler.EnrichContext(ctx, c), req.GetEnvironmentKey(), req.GetPipelineKey(), req.GetType(), req.GetMinVersion(), req.GetMaxVersion(), req.GetIsLatest())
	if err != nil {
		c.JSON(consts.StatusOK, &config.ConfigListResponse{
			Code:  consts.StatusInternalServerError,
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}
	// 确保当列表为空时返回空数组而不是null
	if list == nil {
		list = make([]*common.ResourceConfig, 0)
	}
	c.JSON(consts.StatusOK, &config.ConfigListResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &config.ConfigListData{
			Total: int32(len(list)),
			List:  list,
		},
	})
}

// Detail .
// @router /api/v1/config/detail [GET]
func Detail(ctx context.Context, c *app.RequestContext) {
	req := &config.ConfigDetailRequest{
		EnvironmentKey: c.Query("environment_key"),
		PipelineKey:    c.Query("pipeline_key"),
		ResourceKey:    c.Query("resource_key"),
	}
	if req.EnvironmentKey == "" || req.PipelineKey == "" || req.ResourceKey == "" {
		c.JSON(consts.StatusOK, &config.ConfigDetailResponse{
			Code:  consts.StatusBadRequest,
			Msg:   "error",
			Error: "environment_key, pipeline_key and resource_key are required",
		})
		return
	}
	cfg, err := svc.GetConfigDetail(handler.EnrichContext(ctx, c), req.GetEnvironmentKey(), req.GetPipelineKey(), req.GetResourceKey())
	if err != nil {
		status := consts.StatusInternalServerError
		if errors.Is(err, service.ErrResourceNotFound) {
			status = consts.StatusNotFound
		}
		c.JSON(consts.StatusOK, &config.ConfigDetailResponse{
			Code:  int32(status),
			Msg:   "error",
			Error: err.Error(),
		})
		return
	}
	c.JSON(consts.StatusOK, &config.ConfigDetailResponse{
		Code: consts.StatusOK,
		Msg:  "OK",
		Data: &config.ConfigData{Config: cfg},
	})
}
