// Code generated by hertz generator.

package system

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	common "github.com/yi-nology/rainbow_bridge/biz/model/common"
	system "github.com/yi-nology/rainbow_bridge/biz/model/system"
)

// Init .
// @router /api/v1/system/init [GET]
func Init(ctx context.Context, c *app.RequestContext) {
	var err error
	var req common.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(system.InitResponse)

	c.JSON(consts.StatusOK, resp)
}

// BusinessKeys .
// @router /api/v1/system/business-keys [GET]
func BusinessKeys(ctx context.Context, c *app.RequestContext) {
	var err error
	var req common.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(system.BusinessKeyListResponse)

	c.JSON(consts.StatusOK, resp)
}

// Realtime .
// @router /api/v1/system/realtime [GET]
func Realtime(ctx context.Context, c *app.RequestContext) {
	var err error
	var req common.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(system.RealtimeResponse)

	c.JSON(consts.StatusOK, resp)
}

// Health .
// @router /api/v1/system/health [GET]
func Health(ctx context.Context, c *app.RequestContext) {
	var err error
	var req common.Empty
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(common.OperateResponse)

	c.JSON(consts.StatusOK, resp)
}
