// Code generated by hertz generator.

package system

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	"github.com/yi-nology/rainbow_bridge/biz/model/api"
	"github.com/yi-nology/rainbow_bridge/biz/service"
	"github.com/yi-nology/rainbow_bridge/pkg/common"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// Init .
// @router /api/v1/system/init [GET]
func Init(ctx context.Context, c *app.RequestContext) {
	initData, err := svc.GetInitData(handler.EnrichContext(ctx, c))
	if err != nil {
		handler.WriteInternalError(c, err)
		return
	}
	c.JSON(consts.StatusOK, common.CommonResponse{
		Code: consts.StatusOK,
		Data: initData,
	})
}

// BusinessKeys .
// @router /api/v1/system/business-keys [GET]
func BusinessKeys(ctx context.Context, c *app.RequestContext) {
	keys, err := svc.ListBusinessKeys(handler.EnrichContext(ctx, c))
	if err != nil {
		handler.RespondError(c, consts.StatusInternalServerError, err)
		return
	}
	c.JSON(consts.StatusOK, &api.BusinessKeyListResponse{List: keys})
}

// Realtime .
// @router /api/v1/system/realtime [GET]
func Realtime(ctx context.Context, c *app.RequestContext) {
	payload, err := svc.GetRealtimeStaticConfig(handler.EnrichContext(ctx, c))
	if err != nil {
		handler.WriteInternalError(c, err)
		return
	}
	c.JSON(consts.StatusOK, payload)
}

// Health .
// @router /api/v1/system/health [GET]
func Health(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, common.CommonResponse{
		Code: consts.StatusOK,
		Msg:  "ok",
	})
}
