// Code generated by hertz generator.

package system

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	common "github.com/yi-nology/rainbow_bridge/biz/model/common"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

var svc *service.Service

func SetService(s *service.Service) {
	svc = s
}

// BusinessKeyListResponse for backward compatibility
type BusinessKeyListResponse struct {
	List []string `json:"list"`
}

// BusinessKeys .
// @router /api/v1/system/business-keys [GET]
// DEPRECATED: Use environment and pipeline management instead.
func BusinessKeys(ctx context.Context, c *app.RequestContext) {
	keys, err := svc.ListBusinessKeys(handler.EnrichContext(ctx, c))
	if err != nil {
		handler.RespondError(c, consts.StatusInternalServerError, err)
		return
	}
	c.JSON(consts.StatusOK, &BusinessKeyListResponse{List: keys})
}

// Realtime .
// @router /api/v1/system/realtime [GET]
func Realtime(ctx context.Context, c *app.RequestContext) {
	// Use default environment and pipeline for realtime config
	payload, err := svc.GetRealtimeStaticConfig(handler.EnrichContext(ctx, c), "default", "default")
	if err != nil {
		handler.WriteInternalError(c, err)
		return
	}
	c.JSON(consts.StatusOK, payload)
}

// Health .
// @router /api/v1/system/health [GET]
func Health(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, &common.OperateResponse{
		Code: consts.StatusOK,
		Msg:  "ok",
	})
}
