// Code generated by hertz generator.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/yi-nology/rainbow_bridge/biz/handler"
	"github.com/yi-nology/rainbow_bridge/biz/handler/asset"
	"github.com/yi-nology/rainbow_bridge/biz/handler/config"
	environmenthandler "github.com/yi-nology/rainbow_bridge/biz/handler/environment"
	pipelinehandler "github.com/yi-nology/rainbow_bridge/biz/handler/pipeline"
	"github.com/yi-nology/rainbow_bridge/biz/handler/system"
	systemconfighandler "github.com/yi-nology/rainbow_bridge/biz/handler/system_config"
	"github.com/yi-nology/rainbow_bridge/biz/handler/transfer"
	assetrouter "github.com/yi-nology/rainbow_bridge/biz/router/asset"
	configrouter "github.com/yi-nology/rainbow_bridge/biz/router/config"
	"github.com/yi-nology/rainbow_bridge/biz/router/environment"
	"github.com/yi-nology/rainbow_bridge/biz/router/pipeline"
	systemrouter "github.com/yi-nology/rainbow_bridge/biz/router/system"
	"github.com/yi-nology/rainbow_bridge/biz/router/system_config"
	transferrouter "github.com/yi-nology/rainbow_bridge/biz/router/transfer"
	"github.com/yi-nology/rainbow_bridge/biz/service"
)

// InitHandlers initializes all handler packages with the service instance.
func InitHandlers(svc *service.Service) {
	config.SetService(svc)
	asset.SetService(svc)
	transfer.SetService(svc)
	system.SetService(svc)
	environmenthandler.SetService(svc)
	pipelinehandler.SetService(svc)
	systemconfighandler.SetService(svc)
}

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	system_config.Register(r)

	environment.Register(r)

	pipeline.Register(r)

	assetrouter.Register(r)
	configrouter.Register(r)
	systemrouter.Register(r)
	transferrouter.Register(r)

	// Health Check
	r.GET("/ping", handler.Ping)
}
