// Code generated by hertz generator.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	asset "github.com/yi-nology/rainbow_bridge/biz/router/asset"
	config "github.com/yi-nology/rainbow_bridge/biz/router/config"
	system "github.com/yi-nology/rainbow_bridge/biz/router/system"
	transfer "github.com/yi-nology/rainbow_bridge/biz/router/transfer"
)

// GeneratedRegister registers routers generated by IDL.
// This function is kept for compatibility but is now empty as routes
// are registered directly via RegisterResourceRoutes.
func GeneratedRegister(r *server.Hertz) {
	// Routes are now registered via RegisterResourceRoutes
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	asset.Register(r)

	config.Register(r)

	system.Register(r)

	transfer.Register(r)

}
