// Code generated by hertz generator.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
// This function is kept for compatibility but is now empty as routes
// are registered directly via RegisterResourceRoutes.
func GeneratedRegister(r *server.Hertz) {
	// Routes are now registered via RegisterResourceRoutes
}
