name: Build Docker Frontend

on:
  workflow_call:
    inputs:
      base_path:
        description: 'Base path for deployment'
        required: false
        default: ''
        type: string
    outputs:
      frontend_image_tags:
        description: 'Tags for Frontend Docker image'
        value: ${{ jobs.docker-frontend.outputs.frontend_image_tags }}

env:
  IMAGE_NAME: ghcr.io/yi-nology/rainbow_bridge-frontend

jobs:
  docker-frontend:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    
    outputs:
      frontend_image_tags: ${{ steps.meta-frontend.outputs.tags }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (Frontend)
        id: meta-frontend
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          target: frontend
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          build-args: |
            GO_VERSION=1.25
            BASE_PATH=${{ inputs.base_path }}
